version: '3.1'
services:
  spring-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=orxan
      - RABBITMQ_DEFAULT_PASS=8188121